### ISSUE TITLE
No matching manifest on Windows 10

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/ogr2osm-container#1]
Reported by @xijielu

On Windows 10, when running the `docker build -t ogr2osm .` step, he gets the following error:

`no matching manifest for windows/amd64 in the manifest list`

**Comment by olafveerman** [comment]
@kamicut will reproduce on his Windows machine and report back.

**Comment by kamicut** [comment]
I was able to reproduce this. The reason for this is a setting on Docker for Windows that allows you to switch between Linux container technology and Windows container tech. This repo is made for Linux containers so [you must switch to Linux containers](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers) in the menu bar.
